name: "HLint check"

on:
  pull_request:
    branches:
      - '**'

jobs:
  hlint:
    name: "Hlint check run"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Installing'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.8'

    - name: 'Checking code'
      uses: rwe/actions-hlint-run@v2
      with:
        hlint-bin: "hlint --with-group=extra --ignore-glob=**/testdata/** --ignore-glob=**/test/data/**"
        fail-on: error
        path: .

