name: "HLint check"

on:
  pull_request:
    branches:
      - '**'

jobs:
  hlint:
    name: "Hlint check run"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: haskell-actions/hlint-setup@v2
      with:
        version: "3.10"
    - uses: haskell-actions/hlint-run@v2
      with:
        path: "."
        fail-on: error
